package xyz.malefic.doppelganger.gradle

import org.gradle.api.DefaultTask
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.Optional
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import java.io.File
import java.net.URLClassLoader

abstract class GenerateSvgResourcesTask : DefaultTask() {
    @get:InputFiles
    abstract val compiledClasses: ConfigurableFileCollection

    @get:InputFiles
    abstract val runtimeClasspath: ConfigurableFileCollection

    @get:InputFile
    @get:Optional
    abstract val metadataFile: RegularFileProperty

    @get:OutputDirectory
    abstract val generatedSvgDir: DirectoryProperty

    @get:Input
    @get:Optional
    abstract val outputPackage: Property<String>

    @get:Input
    @get:Optional
    abstract val outputSubdir: Property<String>

    data class FunctionInfo(
        val packageName: String,
        val functionName: String,
        val fileName: String,
    )

    @TaskAction
    fun generate() {
        val svgOutput = generatedSvgDir.get().asFile
        svgOutput.mkdirs()

        logger.lifecycle("=== Doppelganger Gradle Plugin ===")

        // Try to read from KSP metadata first
        val metadataJson = metadataFile.orNull?.asFile
        val functions =
            if (metadataJson != null && metadataJson.exists()) {
                logger.lifecycle("Reading metadata from KSP output...")
                parseMetadataFile(metadataJson)
            } else {
                logger.lifecycle("No KSP metadata found, scanning for @SvgResource functions...")
                // Fallback to reflection-based scanning
                scanForSvgResourceFunctions()
            }

        if (functions.isEmpty()) {
            logger.lifecycle("No @SvgResource functions found")
            logger.lifecycle("Note: SvgResources accessor is generated by KSP during compilation")
            return
        }

        logger.lifecycle("Found ${functions.size} @SvgResource function(s)")
        logger.lifecycle("Note: SvgResources accessor generated by KSP")

        generateSvgFiles(functions, svgOutput)

        logger.lifecycle("✓ Static SVG file generation complete")
    }

    private fun parseMetadataFile(file: File): List<FunctionInfo> {
        try {
            val json = file.readText()
            val functions = mutableListOf<FunctionInfo>()

            // Simple JSON parsing (assumes well-formed output from KSP processor)
            val entries = json.trim().removeSurrounding("[", "]").split("},")

            for (entry in entries) {
                val cleanEntry = entry.trim().removeSurrounding("{", "}")
                if (cleanEntry.isBlank()) continue

                val props =
                    cleanEntry.split(",").associate { prop ->
                        val (key, value) = prop.split(":", limit = 2)
                        key.trim().removeSurrounding("\"") to value.trim().removeSurrounding("\"")
                    }

                val packageName = props["packageName"] ?: ""
                val functionName = props["functionName"] ?: continue
                val fileName = props["fileName"] ?: continue
                val resourceName = props["resourceName"] ?: functionName

                functions.add(
                    FunctionInfo(
                        packageName = packageName,
                        functionName = functionName,
                        fileName = resourceName,
                    ),
                )

                logger.lifecycle("  → Found: $packageName.$functionName from $fileName.kt -> $resourceName.svg")
            }

            return functions
        } catch (e: Exception) {
            logger.warn("Failed to parse metadata file: ${e.message}")
            return emptyList()
        }
    }

    private fun scanForSvgResourceFunctions(): List<FunctionInfo> {
        // Create classloader with compiled classes and dependencies
        val classpathUrls =
            (compiledClasses.files + runtimeClasspath.files)
                .filter { it.exists() }
                .map { it.toURI().toURL() }
                .toTypedArray()

        val classLoader = URLClassLoader(classpathUrls, this.javaClass.classLoader)

        return try {
            findSvgResourceFunctions(classLoader)
        } catch (e: ClassNotFoundException) {
            logger.lifecycle("⚠ Cannot load annotation class (JS-only project?)")
            logger.lifecycle("⚠ SVG generation skipped - use SvgResources accessor at runtime")
            emptyList()
        }
    }

    private fun findSvgResourceFunctions(classLoader: ClassLoader): List<FunctionInfo> {
        val functions = mutableListOf<FunctionInfo>()
        val annotationClassRaw = classLoader.loadClass("xyz.malefic.doppelganger.SvgResource")
        val annotationClass =
            try {
                annotationClassRaw.asSubclass(Annotation::class.java)
            } catch (e: ClassCastException) {
                throw ClassNotFoundException("Loaded SvgResource class is not an annotation", e)
            }

        compiledClasses.files.forEach { classDir ->
            if (!classDir.exists() || !classDir.isDirectory) return@forEach

            classDir
                .walkTopDown()
                .filter { it.extension == "class" }
                .forEach { classFile ->
                    try {
                        val className =
                            classFile
                                .relativeTo(classDir)
                                .path
                                .removeSuffix(".class")
                                .replace(File.separatorChar, '.')

                        val clazz = classLoader.loadClass(className)

                        findTopLevelFunctions(className, clazz, annotationClass, functions)
                    } catch (e: Exception) {
                        logger.debug("Could not load class from {}: {}", classFile, e.message)
                    }
                }
        }

        return functions
    }

    private fun findTopLevelFunctions(
        className: String,
        clazz: Class<*>,
        annotationClass: Class<out Annotation>,
        functions: MutableList<FunctionInfo>,
    ) {
        if (className.endsWith("Kt")) {
            clazz.declaredMethods.forEach { method ->
                if (method.isAnnotationPresent(annotationClass)) {
                    val annotation = method.getAnnotation(annotationClass)
                    val resourceName =
                        try {
                            val resourceNameMethod = annotationClass.getDeclaredMethod("resourceName")
                            (resourceNameMethod.invoke(annotation) as? String)?.takeIf { it.isNotBlank() }
                        } catch (e: Exception) {
                            null
                        }

                    val fileName = resourceName ?: method.name
                    val packageName = clazz.`package`?.name ?: ""

                    logger.lifecycle("  → Found: $packageName.${method.name} -> $fileName")

                    functions.add(
                        FunctionInfo(
                            packageName = packageName,
                            functionName = method.name,
                            fileName = fileName,
                        ),
                    )
                }
            }
        }
    }

    private fun generateSvgFiles(
        functions: List<FunctionInfo>,
        outputDir: File,
    ) {
        logger.lifecycle("Generating static SVG files...")

        // Create classloader for invoking functions
        val classpathUrls =
            (compiledClasses.files + runtimeClasspath.files)
                .filter { it.exists() }
                .map { it.toURI().toURL() }
                .toTypedArray()

        val classLoader = URLClassLoader(classpathUrls, this.javaClass.classLoader)

        var successCount = 0

        functions.forEach { info ->
            try {
                val className =
                    if (info.packageName.isNotEmpty()) {
                        "${info.packageName}.${info.fileName}Kt"
                    } else {
                        "${info.fileName}Kt"
                    }

                val clazz =
                    try {
                        classLoader.loadClass(className)
                    } catch (e: ClassNotFoundException) {
                        logger.warn("  ✗ ${info.fileName}.svg: Could not find class $className")
                        return@forEach
                    }

                val method =
                    clazz.declaredMethods.find { it.name == info.functionName }
                        ?: throw NoSuchMethodException("Method ${info.functionName} not found")

                val svgObject = method.invoke(null)
                val renderMethod =
                    svgObject.javaClass.methods.find { it.name == "render" }
                        ?: throw NoSuchMethodException("render() method not found")

                val svgContent = renderMethod.invoke(svgObject) as String

                writeSvgFile(outputDir, info, svgContent)
                successCount++
            } catch (e: Exception) {
                logger.warn("  ✗ ${info.fileName}.svg: ${e.message}")
                logger.debug("Stack trace:", e)
            }
        }

        if (successCount > 0) {
            logger.lifecycle("✓ Generated $successCount/${functions.size} static SVG files")
        }
    }

    private fun writeSvgFile(
        outputDir: File,
        info: FunctionInfo,
        svgContent: String,
    ) {
        val pkg = outputPackage.getOrElse("")
        val subdir = outputSubdir.getOrElse("")

        val targetDir =
            if (pkg.isNotEmpty()) {
                outputDir.resolve(pkg.replace('.', File.separatorChar))
            } else {
                outputDir
            }.let { dir ->
                if (subdir.isNotEmpty()) dir.resolve(subdir) else dir
            }

        targetDir.mkdirs()

        val svgFile = targetDir.resolve("${info.fileName}.svg")
        svgFile.writeText(svgContent)

        logger.lifecycle("  ✓ ${info.fileName}.svg")
    }
}
