package xyz.malefic.doppelganger.processor

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSFunctionDeclaration

class SvgResourceProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
) : SymbolProcessor {
    override fun process(resolver: Resolver): List<KSAnnotated> {
        val symbols = resolver.getSymbolsWithAnnotation("xyz.malefic.doppelganger.SvgResource")

        val metadata = mutableListOf<FunctionMetadata>()

        symbols
            .filterIsInstance<KSFunctionDeclaration>()
            .forEach { function ->
                val packageName = function.packageName.asString()
                val functionName = function.simpleName.asString()
                val fileName = function.containingFile?.fileName?.removeSuffix(".kt") ?: ""

                val annotation =
                    function.annotations.first {
                        it.shortName.asString() == "SvgResource"
                    }
                val resourceName =
                    annotation.arguments
                        .find { it.name?.asString() == "resourceName" }
                        ?.value as? String

                val finalResourceName = resourceName?.takeIf { it.isNotBlank() } ?: functionName

                metadata.add(
                    FunctionMetadata(
                        packageName = packageName,
                        functionName = functionName,
                        fileName = fileName,
                        resourceName = finalResourceName,
                    ),
                )

                logger.info("Found @SvgResource: $packageName.$functionName in $fileName.kt -> $finalResourceName")
            }

        if (metadata.isNotEmpty()) {
            generateAccessorCode(metadata)
            writeMetadata(metadata)
        }

        return emptyList()
    }

    private fun generateAccessorCode(metadata: List<FunctionMetadata>) {
        val file =
            codeGenerator.createNewFile(
                dependencies = Dependencies.ALL_FILES,
                packageName = "xyz.malefic.doppelganger.generated",
                fileName = "SvgResources",
            )

        file.bufferedWriter().use { writer ->
            writer.appendLine("// Generated by Doppelganger KSP Processor")
            writer.appendLine("// DO NOT EDIT - This file is automatically generated")
            writer.appendLine("@file:Suppress(\"unused\", \"RedundantVisibilityModifier\")")
            writer.appendLine()
            writer.appendLine("package xyz.malefic.doppelganger.generated")
            writer.appendLine()
            writer.appendLine("import xyz.malefic.doppelganger.Svg")

            // Import all packages containing icons
            val uniquePackages =
                metadata
                    .map { it.packageName }
                    .filter { it.isNotEmpty() }
                    .toSet()

            uniquePackages.forEach { pkg ->
                metadata
                    .filter { it.packageName == pkg }
                    .forEach { info ->
                        writer.appendLine("import ${info.packageName}.${info.functionName}")
                    }
            }

            writer.appendLine()
            writer.appendLine("/**")
            writer.appendLine(" * Centralized access to all SVG resources marked with @SvgResource.")
            writer.appendLine(" * ")
            writer.appendLine(" * Usage:")
            writer.appendLine(" * ```kotlin")
            writer.appendLine(" * // Get Svg object (lazy-initialized)")
            writer.appendLine(" * val icon: Svg = SvgResources.homeIcon")
            writer.appendLine(" * ")
            writer.appendLine(" * // Get rendered SVG string (cached)")
            writer.appendLine(" * val svgString: String = SvgResources.homeIconSvg")
            writer.appendLine(" * ")
            writer.appendLine(" * // Use in Compose")
            writer.appendLine(" * KobwebSvg(SvgResources.homeIcon)")
            writer.appendLine(" * ```")
            writer.appendLine(" */")
            writer.appendLine("public object SvgResources {")
            writer.appendLine()

            // Generate properties for each icon
            metadata.forEach { info ->
                writer.appendLine("    /**")
                writer.appendLine("     * SVG resource from ${info.packageName}.${info.functionName}()")
                writer.appendLine("     * Lazy-initialized on first access.")
                writer.appendLine("     */")
                writer.appendLine("    public val ${info.resourceName}: Svg by lazy { ${info.functionName}() }")
                writer.appendLine()

                writer.appendLine("    /**")
                writer.appendLine("     * Rendered SVG string for ${info.resourceName}")
                writer.appendLine("     * Cached after first render.")
                writer.appendLine("     */")
                writer.appendLine("    public val ${info.resourceName}Svg: String by lazy { ${info.resourceName}.render() }")
                writer.appendLine()
            }

            // Generate utility properties and functions
            writer.appendLine("    /**")
            writer.appendLine("     * All available SVG resource names.")
            writer.appendLine("     */")
            writer.appendLine("    public val allResourceNames: Set<String> = setOf(")
            metadata.forEachIndexed { index, info ->
                val comma = if (index < metadata.size - 1) "," else ""
                writer.appendLine("        \"${info.resourceName}\"$comma")
            }
            writer.appendLine("    )")
            writer.appendLine()

            writer.appendLine("    /**")
            writer.appendLine("     * Get an SVG resource by name.")
            writer.appendLine("     * @return Svg object or null if not found")
            writer.appendLine("     */")
            writer.appendLine("    public fun getSvg(name: String): Svg? = when (name) {")
            metadata.forEach { info ->
                writer.appendLine("        \"${info.resourceName}\" -> ${info.resourceName}")
            }
            writer.appendLine("        else -> null")
            writer.appendLine("    }")
            writer.appendLine()

            writer.appendLine("    /**")
            writer.appendLine("     * Render all SVG resources to a map.")
            writer.appendLine("     * Useful for bulk export or testing.")
            writer.appendLine("     */")
            writer.appendLine("    public fun renderAll(): Map<String, String> = buildMap {")
            metadata.forEach { info ->
                writer.appendLine("        put(\"${info.resourceName}\", ${info.resourceName}Svg)")
            }
            writer.appendLine("    }")
            writer.appendLine("}")
        }

        logger.info("Generated SvgResources accessor with ${metadata.size} icons")
    }

    private fun writeMetadata(metadata: List<FunctionMetadata>) {
        val file =
            codeGenerator.createNewFile(
                dependencies = Dependencies.ALL_FILES,
                packageName = "",
                fileName = "svg-resources",
                extensionName = "json",
            )

        file.bufferedWriter().use { writer ->
            writer.write("[\n")
            metadata.forEachIndexed { index, meta ->
                writer.write("  {")
                writer.write("\"packageName\":\"${meta.packageName}\",")
                writer.write("\"functionName\":\"${meta.functionName}\",")
                writer.write("\"fileName\":\"${meta.fileName}\",")
                writer.write("\"resourceName\":\"${meta.resourceName}\"")
                writer.write("}")
                if (index < metadata.size - 1) writer.write(",")
                writer.write("\n")
            }
            writer.write("]\n")
        }

        logger.info("Generated metadata for ${metadata.size} @SvgResource functions")
    }

    data class FunctionMetadata(
        val packageName: String,
        val functionName: String,
        val fileName: String,
        val resourceName: String,
    )
}
